name: flutter_movie_app
description: "A Movie App."

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: 3.3.0
  fpdart: ^1.1.0
  mocktail: ^1.0.3
  get_it: 7.6.4
  provider: 6.1.1
  shimmer: ^3.0.0
  http: ^1.1.2
  hive: ^2.2.3
  url_launcher: 6.2.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1
  build_runner: 2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lottie/
    - assets/svg/